
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function downloadAsTxt(content: string, filename: string) {
    const header = `
*************************************************
*                                               *
*                   PRAGYAN AI                    *
*                                               *
*************************************************

`;

    const footer = `

*************************************************
*              Generated by Pragyan AI            *
*************************************************
`;

    const fullContent = header + content + footer;

    const blob = new Blob([fullContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
